<!--
This code is used to display selected categories on the home page and
is called in cms static block Subsubcategories which is inserted into 
the cms page home. This page uses the catalog/navigation block type as
set in its cms static block.
-->

<?php 
$parentCategoryId = 2;
$cat = Mage::getModel('catalog/category')->load($parentCategoryId);
$subcats = $cat->getChildren();

$cache=array();
$extras=array();

class Assem {
    public $cacheData=array();
    public $extrasData=array();
}
var_dump(Mage::getConfig()->getBlockClassName('customvariables/date'));
var_dump(mageFindClassFile('MyModule_Homebanner_Block_Homebanner'));
var_dump(mageFindClassFile('MyModule_Customvariables_Block_Data_Date'));
new MyModule_Homebanner_Block_Homebanner;
new MyModule_Customvariables_Block_Data_Date;
echo $this->getLayout()->createBlock('homebanner/homebanner')->setTemplate('homebanner/homebanner.phtml')->toHtml();
echo $this->getLayout()->createBlock('customvariables/date')->setTemplate('customvariables/date.phtml')->toHtml();

echo 'handles: ';
Zend_Debug::dump($this->getLayout()->getUpdate()->getHandles());
$block = $this->getLayout()->getBlock('THEME_frontend_tt_theme165');

 $childBlockNameCollection=$block ->_sortedChildren;
  echo "<pre>";
 print_r($childBlockNameCollection);
 echo "</pre>";

// $aliasName='default';
// Zend_Debug::dump($block->getChild($aliasName));



function get_cat($dataset, $instance) {

    $out = new Assem();
    
    $sortkey=0;
    $data="";
    
    foreach(explode(',',$dataset) as $subDataset) {
      $_category = Mage::getModel('catalog/category')->load($subDataset);
      if($_category->getIsActive()) {
        if ($_category->getCatalogCategory() == "1") {
          $data=assemble_html($_category, $instance);
            if ($sortkey=$_category->getHbSort()) { 
              $out->cacheData[$sortkey]=$data;
            } else {
              $out->extrasData[]=$data;
            }
          }
      }
    }
    
    return $out;
}   

function assemble_html($string, $instance) {
    $htmldata='<a href="'.$string->getURL().'" id="customid"><script type="text/javascript">swapid();</script><span class="banner-image"><img class="banner-image" src="'.Mage::getBaseUrl("media") . "catalog" . DS . "category" . DS . $string->getThumbnail().'" alt="'.$instance->htmlEscape($string->getName()).'" /><span class="css3bannergradient" /></span></span><span class="banner-title">'.$string->getName().'</span></a>';
    
    return $htmldata;
}



echo '
<script type="text/javascript">
<!--
  var styleid="";
  var removePad="";
  var endRemovePad="";
if (navigator.userAgent.search("MSIE") >= 0){
    styleid="ieresize";
    removePad="<div class=\'clipping\'>";
    endRemovePad = "</div>";
} else if (navigator.userAgent.search("Chrome") >= 0){
    styleid="gcresize";
} else if (navigator.userAgent.search("Firefox") >= 0){
    styleid="";
} else if (navigator.userAgent.search("Safari") >= 0 && navigator.userAgent.search("Chrome") < 0) {//<< Here
    styleid="";
} else if (navigator.userAgent.search("Opera") >= 0) {
    styleid="";
} else {
    styleid="";
}

// Adjust styles to suit browser.
function swapid() {
  document.getElementById("customid").id = styleid;
}
//-->
</script>';


// if IE insert opening divide used with css to remove left padding.
echo '<script type="text/javascript">
<!-- 
document.write(removePad);
//-->
</script>';
echo '<div class="home-banners">';

$current=$this;
$outContainer = get_cat($subcats, $current);
$cache = $outContainer->cacheData;
$extras = $outContainer->extrasData;

foreach(explode(',',$subcats) as $subCatid) {
  $_category = Mage::getModel('catalog/category')->load($subCatid);
  if($_category->getIsActive()) {

    $sub_cat = Mage::getModel('catalog/category')->load($_category->getId());
    $sub_subcats = $sub_cat->getChildren();

    $outContainer = get_cat($sub_subcats, $current);
    $cache += $outContainer->cacheData;
    foreach ($outContainer->extrasData as $key => $value) {
      array_push($extras, $value);
    }

  }
}


ksort($cache);
foreach ($cache as $key => $value) {
    echo $value;
}

ksort($extras);
foreach ($extras as $key => $value) {
    echo $value;
}

echo '<div style="clear:left;"></div>';

// if IE insert closing divide to remover left padding.
echo '</div>';
echo '<script type="text/Javascript">
<!--// 
document.write(endRemovePad);
//-->
</script>';


?>