<!-- 
This code is used to display the index at the bottom of pages.
As some editors do not recognise the remark tags for code, I will
also use html remark tags within php for editor compatability.
This code is referenced in the Footer_Bottom_1 cms static block and
uses the catalog/navigation block type.
-->

<?php 
echo '<div class="spacer">&nbsp;</div>';
$_helper = Mage::helper('catalog/category');
$_categories = $_helper->getStoreCategories();
$currentCategory = Mage::registry('current_category');

if (count($_categories) > 0): 
for ($x=3; $x>0; $x--) {	// <!-- 3 columns because rows of divs do not move up after wrapping. -->
$count=$x;	// <!-- Use $x as our offset -->
        echo '<div class="fetchsubscontainer">';
        foreach($_categories as $_category):	// <!-- Lets cycle through & display every 3rd category from our offset with its children -->
            if ($count==3) {
                $count=0; 
                echo '<div class="fetchsubselement"><h4><a href="' . $_helper->getCategoryUrl($_category) . '">';
                echo $_category->getName();
                echo '</a></h4>';
                $_category = Mage::getModel('catalog/category')->load($_category->getId());
                $_subcategories = $_category->getChildrenCategories();
                if (count($_subcategories) > 0):	// <!-- Now cycle through & display all its children -->
                        foreach($_subcategories as $_subcategory):
                                echo '<a class="fetchsubslink" href="' . $_helper->getCategoryUrl($_subcategory) . '">';
                                    echo $_subcategory->getName();
                                echo '</a><br />';
                        endforeach;
                endif;
                echo '</div>';
            }
            $count++;                          
        endforeach;
        echo '</div>';
}
echo '<div class="clear">&nbsp;</div>';
endif;





/* The old code, kept for reference incase we need deeper levels of subcategories displayed.*/


// $count=0;

// $parentCategoryId = 2;
// $cat = Mage::getModel('catalog/category')->load($parentCategoryId);
// $subcats = $cat->getChildren();


    /* Get the categories that are active for the store */
//    $_main_categories=$this->getStoreCategories();
     
    /* Get the current category the user is in */
//    $_current_category=$this->getCurrentCategory();
     
    /* Get the current category path */
//    $_categorypath = $this->getCurrentCategoryPath();
//echo '<table style="width: 95%;" /><tr>';
// echo '<ul>';

//    if ($_main_categories):
        /* This bit cycles through the categories - setting the next one to current */
//        foreach ($_main_categories as $_main_category):
//          if($_main_category->getIsActive()): 
//               $cur_category=Mage::getModel('catalog/category')->load($_main_category->getId());
//               $layer = Mage::getSingleton('catalog/layer');
//               $layer->setCurrentCategory($cur_category);   
 

     
    /* Write the main categories */   
//    if ($count==3) { $count=0; echo '</tr><tr>'; }        
//    echo '<td style="width: 31%; padding-left: 10%; padding-bottom: 20px;"><h4><a href="'.$this->getCurrentCategory()->getUrl().'" title="View the products for the "'.$this->getCurrentCategory()->getName().'" category">'.$this->getCurrentCategory()->getName().'</a></h4>';
    // echo '<li><a href="' . $this->getCurrentCategory()->getUrl() . '">' . $this->getCurrentCategory()->getName() . '</a></li>';
               
//                $children = $_main_category->getChildren();                 
//                foreach ($children as $child):
//              echo '<li><a href="' . $child->getUrl() . '" title="View the products for the "' . $child->getName() . '" category">' . $child->getName() . '</a></li>';
                  // echo $child->getName() . '<br />';
//               endforeach;    
//    echo '</td>';

//    $count++;   
    /* Check the category variable loop against the current category path if it is - print sub categories */
//    if ($this->getCurrentCategory()->getId()):
//      $_maincategorylisting=$this->getCurrentCategory();
//      $_categories=$this->getCurrentChildCategories();
//      if($_categories->count()):
//         echo '<ul>';
//         foreach ($_categories as $_category):
//           if($_category->getIsActive()):                   
//               $cur_subcategory=Mage::getModel('catalog/category')->load($_category->getId());
//               $layer = Mage::getSingleton('catalog/layer');
//               $layer->setCurrentCategory($cur_subcategory); 
//               echo '<li><a href="' . $this->getCategoryUrl($_category) . '"' . $_category->getName() . '</a></li>';
//           endif;
//         endforeach;
//      echo '</ul>';
     /* This resets the category back to the original pages category
    ****     If this is not done, subsequent calls on the same page will use the last category
    ****    in the foreach loop
    */ 
     
//    endif;
     
//    endif;
                                     
//    $layer->setCurrentCategory($_current_category);
                                                                 

//    endif;
//    endforeach;
//    else:

//    echo '<p> $_main_categories array was empty.</p>';
//    echo '<p>This might be because you are referencing this phtml file with a wrong type attribute. You should use <block type="catalog/navigation" ... /> !</p>';
//    endif; 
//echo '</tr></table>';


 /* Best Seller*/
/* function getMostViewedProducts()
{      
    /**
     * Number of products to display
     * You may change it to your desired value
     */
/*    $productCount = 5; */
     
    /**
     * Get Store ID
     */
/*    $storeId    = Mage::app()->getStore()->getId();      */
     
    /**
     * Get most viewed product collection
     */
/*    $products = Mage::getResourceModel('reports/product_collection')
        ->addAttributeToSelect('*')     
        ->setStoreId($storeId)
        ->addStoreFilter($storeId)
        ->addViewsCount()
        ->setPageSize($productCount);
     
    Mage::getSingleton('catalog/product_status')
            ->addVisibleFilterToCollection($products);
    Mage::getSingleton('catalog/product_visibility')
            ->addVisibleInCatalogFilterToCollection($products);
     
    return $products;
}
foreach ($products=getMostViewedProducts() as $product) {
   if($product->getIsActive()): 
     echo $product;
   endif;
} */



/* echo '<table style="width: 95%;" /><tr>';
foreach(explode(',',$subcats) as $subCatid)
{

  $_category = Mage::getModel('catalog/category')->load($subCatid);

  
  if($_category->getIsActive()) {
    arsort($_category);

    // echo '<div style="float: left; margin: 8px; padding: 20px; width: 31%; height: 125px;" />';
    if ($count==3) { $count=0; $verifycount++; echo '</tr><tr>'; }
    echo '<td style="width: 31%; padding-left: 10%; padding-bottom: 20px;"><h4><a href="'.$_category->getURL().'" title="View the products for the "'.$_category->getName().'" category">'.$_category->getName().'</a></h4>';
    $sub_cat = Mage::getModel('catalog/category')->load($_category->getId());
    $sub_subcats = $sub_cat->getChildren();
    foreach(explode(',',$sub_subcats) as $sub_subCatid)
    {


          $_sub_category = Mage::getModel('catalog/category')->load($sub_subCatid);
          if($_sub_category->getIsActive()) {
              echo '<li><a href="'.$_sub_category->getURL().'" title="View the products for the "'.$_sub_category->getName().'" category">'.$_sub_category->getName().'</a></li>';
          }
     }
    // echo '</div>';

  echo '</td>';
  } 
  $count++;
}

echo '</tr></table>';
// echo 'I counted ' . $verifycount . ' rows created'; */
?>