<!--
This code is used to display the child categories 
in each parent category. It is written to be called in 
admin panel > catalog > manage categories > category > display settings
-->

<?php
$_categories = Mage::getSingleton('catalog/layer')->getCurrentCategory();
$categories = $_categories->getCollection()
        ->addAttributeToSelect(array('name', 'thumbnail'))
        ->addAttributeToFilter('is_active', 1)
        ->addIdFilter($_categories->getChildren())
        ->setOrder('position', 'ASC');
?>

<div class="sub-banners" />
    <?php foreach ($categories as $category): ?>

          <a href="<?php echo $category->getUrl() ?>"><span class="banner-image"><img src="<?php echo Mage::getBaseUrl('media') . 'catalog' . DS . 'category' . DS . $category->getThumbnail() ?>" class="banner-image" alt="<?php echo $this->htmlEscape($category->getName()) ?>" /></span><span class="css3bannergradient"></span><span class="banner-title"><?php echo $this->htmlEscape($category->getName()) ?></span></a>
   
    <?php endforeach; ?>
</div>